"""baseline schema

Revision ID: bd9c1b9d4058
Revises: 
Create Date: 2026-06-14 00:49:50.185692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9c1b9d4058'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ios_identifier', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('product_version', sa.String(length=64), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'LOCKED', 'UNLOCKED', 'INDEXING', 'INDEXED', name='backupstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('decryption_status', sa.Enum('PENDING', 'DECRYPTING', 'DECRYPTED', 'FAILED', name='decryptionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('decrypted_path', sa.String(length=1024), nullable=True),
    sa.Column('decryption_error', sa.Text(), nullable=True),
    sa.Column('decrypted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexing_progress', sa.BigInteger(), nullable=True),
    sa.Column('indexing_total', sa.BigInteger(), nullable=True),
    sa.Column('indexing_artifact', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_ios_identifier'), ['ios_identifier'], unique=True)

    op.create_table('artifact_search_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('artifact_ref', sa.String(length=255), nullable=False),
    sa.Column('display_text', sa.String(length=512), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_search_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_search_index_artifact_ref'), ['artifact_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_search_index_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_search_index_backup_id'), ['backup_id'], unique=False)

    op.create_table('calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('calendar_identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendars_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index('ix_calendars_backup_identifier', ['backup_id', 'calendar_identifier'], unique=True)

    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('contact_identifier', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('phones', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_file_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_contact_identifier'), ['contact_identifier'], unique=False)

    op.create_table('message_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_guid', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participant_handles', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_guid')
    )
    with op.batch_alter_table('message_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_conversations_backup_id'), ['backup_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('note_identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_note_identifier'), ['note_identifier'], unique=False)

    op.create_table('photo_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('relative_path', sa.String(length=1024), nullable=True),
    sa.Column('file_id', sa.String(length=128), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_assets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_photo_assets_backup_asset', ['backup_id', 'asset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_photo_assets_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_photo_assets_file_id'), ['file_id'], unique=False)

    op.create_table('whatsapp_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('chat_guid', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_chats', schema=None) as batch_op:
        batch_op.create_index('ix_whatsapp_chats_backup_guid', ['backup_id', 'chat_guid'], unique=True)
        batch_op.create_index(batch_op.f('ix_whatsapp_chats_backup_id'), ['backup_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('event_identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_event_identifier'), ['event_identifier'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_guid', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('is_from_me', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['message_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_message_guid'), ['message_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sent_at'), ['sent_at'], unique=False)

    op.create_table('whatsapp_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('media_type', sa.String(length=64), nullable=True),
    sa.Column('is_from_me', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['whatsapp_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_backup_id'), ['backup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_sent_at'), ['sent_at'], unique=False)

    op.create_table('message_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=True),
    sa.Column('relative_path', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('whatsapp_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=True),
    sa.Column('relative_path', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['whatsapp_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_attachments_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_attachments_message_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_attachments_file_id'))

    op.drop_table('whatsapp_attachments')
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attachments_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_attachments_file_id'))

    op.drop_table('message_attachments')
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_message_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_chat_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_backup_id'))

    op.drop_table('whatsapp_messages')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_messages_message_guid'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_backup_id'))

    op.drop_table('messages')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_event_identifier'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_calendar_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_backup_id'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('whatsapp_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_chats_backup_id'))
        batch_op.drop_index('ix_whatsapp_chats_backup_guid')

    op.drop_table('whatsapp_chats')
    with op.batch_alter_table('photo_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_assets_file_id'))
        batch_op.drop_index(batch_op.f('ix_photo_assets_backup_id'))
        batch_op.drop_index('ix_photo_assets_backup_asset')
        batch_op.drop_index(batch_op.f('ix_photo_assets_asset_id'))

    op.drop_table('photo_assets')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_note_identifier'))
        batch_op.drop_index(batch_op.f('ix_notes_backup_id'))

    op.drop_table('notes')
    with op.batch_alter_table('message_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_conversations_backup_id'))

    op.drop_table('message_conversations')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_contact_identifier'))
        batch_op.drop_index(batch_op.f('ix_contacts_backup_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index('ix_calendars_backup_identifier')
        batch_op.drop_index(batch_op.f('ix_calendars_backup_id'))

    op.drop_table('calendars')
    with op.batch_alter_table('artifact_search_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_search_index_backup_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_search_index_artifact_type'))
        batch_op.drop_index(batch_op.f('ix_artifact_search_index_artifact_ref'))

    op.drop_table('artifact_search_index')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_ios_identifier'))

    op.drop_table('backups')
    # ### end Alembic commands ###
