"""add photo geotags

Revision ID: d1e2f3a4b5c6
Revises: 93709857cae8
Create Date: 2026-06-14 20:30:00.000000

Adds nullable latitude/longitude columns to photo_assets so geotagged photos can
be plotted on the map. Hand-written (not autogenerated) to avoid the spurious
SQLite NUMERIC->UUID alter noise; batch_alter_table keeps it SQLite-compatible.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2f3a4b5c6'
down_revision: Union[str, None] = '93709857cae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('photo_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table('photo_assets', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
